### ISSUE TITLE
mapped-type example for pandas dataframe?

### ISSUE THREAD

**Issue by dwinston** [muhrin/mincepy#15]
Hi, @muhrin! This looks like a great library! You may remember me from a past OPTiMaDe workshop (2019? Perhaps 2018?). I recall you having great insights.

I'm working on a [project](https://github.com/TRI-AMDD/CAMD/) that is currently saving pandas dataframes as Python pickles, but mincepy seems great for saving them versioned and with metadata. I'm not sure if it will actually fit for the use case, as the dataframes are currently saved to local disk and synced to AWS S3, so the additional overhead of a running MongoDB server may be a drawback. In any case, I would be interested in reading an example in the documentation of creating a mapped type (or whatever mechanism is appropriate -- I am guessing here) for saving/loading/querying-metadata-for pandas dataframes via mincepy.

**Comment by muhrin** [comment]
Hi @dwinston, thanks so much for getting in touch!  And thanks for the kind words.

That's a super nice use case you bring up, and one I'm definitely keen to explore.  Due to my limited time I've just been adding the types that I use daily (e.g. numpy arrays, although even this sits in a private repo for now and should be made pubilc) but I've been looking for an excuse build on what we have, both in terms of the types and the documentation itself so people could be more 'autonomous' in supporting their own use cases.

So let me start with a couple of questions:

1. Would you have the time/will to try implementing this yourself if I add more documentation?  Depending on the internals of dataframes it could be trivial, or a little tricky, hard to say before starting.  If you don't have the time I'm happy to attempt it myself and put it up as a documented example for others.

2. MongoDB is, for now, unavoidable (the kind of query performance I was targeting just wasn't possible without it).  Is this a show stopper for you?  Would a docker container lessen the pain?  Would an free online server be a solution?

CAMD looks great btw, and exactly the kind of poject I'm targeting.

**Comment by dwinston** [comment]
> 1. Would you have the time/will to try implementing this yourself if I add more documentation? Depending on the internals of dataframes it could be trivial, or a little tricky, hard to say before starting. If you don't have the time I'm happy to attempt it myself and put it up as a documented example for others.

I don't have the time at the moment. I could see having the time -- and better use-case fit -- in a few months, which is related to my answer to your second question.

> 2. MongoDB is, for now, unavoidable (the kind of query performance I was targeting just wasn't possible without it). Is this a show stopper for you? Would a docker container lessen the pain? Would an free online server be a solution?

Not a show stopper. In fact, it may fit in somewhat comfortably. The syncing to AWS S3 is in service of supporting remote workflow execution, but the simplicity of S3 as a key-value store has limitations for performance of more complex queries, especially across metadata. So, in addition to the base simplicity of native local filesystem persistence, an alternative to AWS S3 for (a subset of) data syncing is desirable, and MongoDB could be a good fit for this. Thus, there is motivation for potential usage of MongoDB independent of being able to leverage mincepy.

More of a show-stopper would be the inability of mincepy to deal with dataframes, which I suspect is not the case: as you mentioned, I suspect it may be tricky but not impossible.

**Comment by muhrin** [comment]
Ok, I have a basic implementation of saving and loading a `DataFrame` working: https://github.com/muhrin/mincepy_sci/blob/develop/test/test_pandas_types.py.

Thanks to their `to_/from_dict()` functions it was trivial to add.  It may well be that there are things missing from this in terms of preserving everything in a round trip (i.e. save and load a DF), so more testing definitely required.

Do you have examples, in general terms, of the kinds of queries you would need to perform?  I ask partly because MongoDB (or document based) DBs aren't particularly good at joins (e.g. `Car.owner.name == Person.name`) and in mincePy support is relatively poor.  On the other hand, queries like `Car.owner.name == 'Mike'` are perfectly fast.  Sorry if this is all obvious to you, it's just something people coming from a relational background find frustrating at first.

**Comment by muhrin** [comment]
And yes, I've found this whole MongoDB/mincePy setup quite neat for running workflows.  I have a basic task queue provided by [minkiPy](https://github.com/muhrin/minkipy/) where the tasks themselves are actually mincePy storable so the workers just pull jobs from minkiPy queues which automatically loads the corresponding (python) task object from MongoDB and calls a `run` function.  The arguments to `run` can be arbitrary mincePy storables (e.g. `DataFrames`) and if anything crashes/conection gets lost/etc it gets requeued and picked up by the next worker who comes across it.

**Comment by muhrin** [comment]
For reference, I've now put up a plugin for various scientific data types (including `DataFrame`s) here: https://pypi.org/project/mincepy-sci/.

**Comment by dwinston** [comment]
Thanks! The [ase_types](https://github.com/muhrin/mincepy_sci/blob/b06f7843d639093c1ae4461bdc9faa6d755be09a/mincepy_sci/ase_types.py) module is also helpful, as CAMD dataframes may include [pymatgen](https://pymatgen.org/) and other specialized objects, so the types may need more extending. But, this is a good proof-of-concept -- thank you!

> Do you have examples, in general terms, of the kinds of queries you would need to perform? I ask partly because MongoDB (or document based) DBs aren't particularly good at joins (e.g. Car.owner.name == Person.name) and in mincePy support is relatively poor. On the other hand, queries like Car.owner.name == 'Mike' are perfectly fast. Sorry if this is all obvious to you, it's just something people coming from a relational background find frustrating at first.

I have experience with MongoDB, so I am used to the idea of creating separate collections with data de-normalized so as to support access patterns that do not require joins. I envision complex queries supported by other collections -- the important idea here is that there may be a decent reason to operate a MongoDB server anyway, so it would not be for mincePy functionality alone -- an easier sell. :)

**Comment by muhrin** [comment]
Closing this issue.  We now have pandas and pytmatgen support in https://github.com/muhrin/mincepy_sci/.
