### ISSUE TITLE
How to connect to local database?

### ISSUE THREAD

**Issue by stefaneidelloth** [muhrin/mincepy#18]
In the readme is stated "either in your local database or one shared with your collaborators".

=> Does that mean that mincepy does not only support MongoDb but also different database types? 
Support for a file based database (e.g. unqlite) or plain JSON would be great.

Could you please clarify the difference between "local" and "shared" mode?

**Comment by muhrin** [comment]
Hi @stefaneidelloth ,

sorry for the late reply, for some reason I didn't get the notification of your message.

By 'local' I just meant one running on your own machine.  For example, I run on Ubuntu where you can install a local MongoDB instance using

`sudo apt install mongodb-server`

This way I have a local server (with no ports open to the outside and no need to set up a username/password) and I can use `mincepy` simply using:

```
import mincepy
mincepy.connect('mongodb://localhost')
```

The 'shared' mode would be the same procedure (as I have, for example, with my colleagues in the office) but you would need to create user accounts on the mongo DB installation and open ports so you and whoever you share it with could access the server.

Regarding support for difference database types: the simple answer is no, this is not implemented (mainly because I found using MongoDB so easy that it wasn't a priority).  If you wanted to implement a different backend you would need to implement the `mincepy.Archive` interface with a concrete class for the backend you had in mind, although this is a task that would require quite some exertise.

Let me know if you would find any of this useful to be included/expanded upon in the documentation and I can add it.

**Comment by stefaneidelloth** [comment]
Thank you for clarification. In the meanwhile I found jsonpickle which might be an option for local JSON storage and version control of the "database".

**Comment by muhrin** [comment]
No worries.  Yes, absolutely JSON is a fine choice for local storage of data.

I'll close this issue but feel free to open another issue if you have any other questions about mincepy.
